### PR TITLE
turn max length consts into global vars

### PR DESCRIPTION
**Pull request by whyrusleeping**
Sometimes you just want to set these globally

### CODE REVIEW

**Review by ericvolp12 — APPROVED** [review]

**Comment by whyrusleeping** [comment]
steb im still eventually interested in getting a thumbs up from you but it seems low risk enough to merge this

**Comment by Stebalien** [comment]
Can we make it an option during codegen instead? Maybe a new `WriteEncodersToFile` that includes a `Config` object with options like:

- Representation (tuple/map).
- Default max bytestring length.
- Default max array length.

Etc?

Globals like this can make two different seemingly compatible libraries can't actually be used together.

**Comment by Stebalien** [comment]
Hm. Even better:

```go
type Gen struct {
    TupleEncoding  []any
    MapEncoding    []any
    PackageName    string
    MaxByteLength  int    // 0 for default
    MaxArrayLength int    // 0 for default
}

func (g *Gen) WriteTo(filename string) error {
    // ...
}
```

(or something like that)

**Comment by whyrusleeping** [comment]
Oh i like that appoach

**Pull request merged**
